### ISSUE TITLE
Configure bitcoind?

### ISSUE THREAD

**Issue by anandpatel010** [RoninDojo/RoninDojo#21]
Is it possible for example if I wanted to enable pruning?

**Comment by anandpatel010** [comment]
And Merry Christmas :) 🎄

**Comment by BTCxZelko** [comment]
Dojo is a backend server and is required to be a full node. So unfortunately pruned is not an option.

**Comment by anandpatel010** [comment]
Ok thanks, Gotta buy an ssd then!
