### ISSUE TITLE
Decoupling bitcoin core from dojo

### ISSUE THREAD

**Issue by ghost** [RoninDojo/RoninDojo#35]
It would be beneficial to be able to choose whether to upgrade bitcoin core with new dojo upgrades instead of a new core version being integrated with dojo as a complete package upgrade. In the case of another contentious fork (soft or otherwise), I believe it would be beneficial to give people the option of not upgrading if they do not want to and still enjoy other dojo developments that are backwards compatible. I would love to know others opinions on this.

**Comment by BTCxZelko** [comment]
Thanks for the comment.

Given that this is a docker install. You can manually go into dojo/docker/my-dojo/bitcoin/Dockerfile and modify which bitcoin core you would like to use. 

In the event that a contentious fork comes up... I will speak to the Dojo team about integrating an option. However, we cannot guarantee 100% compatibility or features on a core version not currently inside Dojo.
